# This is a basic workflow to help you get started with Actions

name: tests

# Controls when the action will run.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ '*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install

    - run: npm test
      env:
        CI: true
